
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-indexer
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: do-block-storage