apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-indexer
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
    {{- if .Values.rollback }}
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    {{- end }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.rollback }}
  dataSource:
    name: wazuh-indexer-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  {{- end }}
  resources:
    requests:
      storage: 500Mi
  storageClassName: do-block-storage