
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-indexer
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.historyAndRollback }}
  dataSource:
    name: wazuh-indexer-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  {{- end }}
  resources:
    requests:
      storage: 500Mi
  storageClassName: do-block-storage