kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wazuh-indexer-certs
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 20Mi