indexer:
  replicas: 1
  repository: 'wazuh/wazuh-indexer'
  tag: '4.8.0'
  resources:
    limits:
      cpu: 500m
      memory: 1564Mi
  environments:
    java_opts: '-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true'
    cluster_name: 'wazuh'
    network_host: '0.0.0.0'
    discovery_service: 'wazuh-indexer'
