indexer:
  replicas: 1
  repository: 'wazuh/wazuh-indexer'
  tag: '4.5.0'
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
  environments:
    java_opts: '-Xms512m -Xmx512m'
    cluster_name: 'wazuh'
    network_host: '0.0.0.0'
    discovery_service: 'wazuh-indexer'
wazuh:
  repository: 'wazuh/wazuh-manager'
  tag: '4.5.0'
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
dashboard:
  replicas: 1
  repository: 'wazuh/wazuh-dashboard'
  tag: '4.5.0'
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
