apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-backups
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
rules:
  - apiGroups:
        - "velero.io"
    resources:
      - backups
    verbs: []