apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "wazuh-manager"
      app.cloud.wazuh.com/node-type: "master"
  serviceName: wazuh-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "wazuh-manager"
        app.kubernetes.io/version: {{ .Values.wazuh.tag }}
        app.cloud.wazuh.com/node-type: "master"
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      name: wazuh-manager-master
    spec:
      volumes:
        - name: wazuh-indexer-certs
          persistentVolumeClaim:
            claimName: wazuh-indexer-certs
        - name: wazuh-manager-config
          configMap:
            name: wazuh-manager-config
      containers:
        - name: wazuh-manager
          image: '{{ .Values.wazuh.repository }}:{{ .Values.wazuh.tag }}'
          {{- if .Values.wazuh.resources }}
          resources:
            {{- toYaml .Values.wazuh.resources | nindent 12 }}
          {{- end }}
          env:
            - name: INDEXER_URL
              value: https://wazuh.indexer:9200
            - name: INDEXER_USERNAME
              value: admin
            - name: INDEXER_PASSWORD
              value: SecretPassword
            - name: FILEBEAT_SSL_VERIFICATION_MODE
              value: full
            - name: SSL_CERTIFICATE_AUTHORITIES
              value: /etc/ssl/root-ca.pem
            - name: SSL_CERTIFICATE
              value: /etc/ssl/filebeat.pem
            - name: SSL_KEY
              value: /etc/ssl/filebeat.key
            - name: API_USERNAME
              value: wazuh-wui
            - name: API_PASSWORD
              value: MyS3cr37P450r.*-
          volumeMounts:
            - name: wazuh-manager-master
              mountPath: /var/ossec/api/configuration
              subPath: wazuh/var/ossec/api/configuration
            - name: wazuh-manager-master
              mountPath: /var/ossec/etc
              subPath: wazuh/var/ossec/etc
            - name: wazuh-manager-master
              mountPath: /var/ossec/logs
              subPath: wazuh/var/ossec/logs
            - name: wazuh-manager-master
              mountPath: /var/ossec/queue
              subPath: wazuh/var/ossec/queue
            - name: wazuh-manager-master
              mountPath: /var/ossec/var/multigroups
              subPath: wazuh/var/ossec/var/multigroups
            - name: wazuh-manager-master
              mountPath: /var/ossec/integrations
              subPath: wazuh/var/ossec/integrations
            - name: wazuh-manager-master
              mountPath: /var/ossec/active-response/bin
              subPath: wazuh/var/ossec/active-response/bin
            - name: wazuh-manager-master
              mountPath: /var/ossec/agentless
              subPath: wazuh/var/ossec/agentless
            - mountPath: /var/ossec/wodles
              name: wazuh-manager-master
              subPath: wazuh/var/ossec/wodles
            - name: wazuh-manager-master
              mountPath: /etc/filebeat
              subPath: filebeat/etc/filebeat
            - name: wazuh-manager-master
              mountPath: /var/lib/filebeat
              subPath: filebeat/var/lib/filebeat
            - name: wazuh-indexer-certs
              mountPath: /etc/ssl
              readOnly: true
            - name: wazuh-manager
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: ossec.conf
              readOnly: true 
          ports:
            - containerPort: 1514
              name: connection
            - containerPort: 1515
              name: enrollment
            - containerPort: 1516
              name: cluster
            - containerPort: 55000
              name: api
  volumeClaimTemplates:
    - metadata:
        name: wazuh-manager-master
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 500Mi
