apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: {{ .Values.indexer.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "wazuh-indexer"
  serviceName: wazuh-indexer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "wazuh-indexer"
        app.kubernetes.io/version: {{ .Values.indexer.tag }}
      name: wazuh-indexer
    spec:
      volumes:
        - name: wazuh-indexer
          persistentVolumeClaim:
            claimName: wazuh-indexer
        - name: wazuh-certificates
          secret:
            secretName: wazuh-certificates
        - name: wazuh-indexer-config
          configMap:
            name: wazuh-indexer-config
      initContainers:
        - name: volume-mount-hack
          image: busybox
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          command:
            - sh
            - '-c'
            - 'chown -R 1000:1000 /var/lib/wazuh-indexer'
          volumeMounts:
            - name: wazuh-indexer
              mountPath: /var/lib/wazuh-indexer
        - name: increase-the-vm-max-map-count
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: wazuh-indexer
          image: '{{ .Values.indexer.repository }}:{{ .Values.indexer.tag }}'
          {{- if .Values.indexer.resources }}
          resources:
            {{- toYaml .Values.indexer.resources | nindent 12 }}
          {{- end }}
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: {{ .Values.indexer.environments.java_opts }}
            - name: CLUSTER_NAME
              value: {{ .Values.indexer.environments.cluster_name }}
            - name: NETWORK_HOST
              value: {{ .Values.indexer.environments.network_host }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DISCOVERY_SERVICE
              value: {{ .Values.indexer.environments.discovery_service }}
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: 'true'
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
          volumeMounts:
            - name: wazuh-indexer
              mountPath: /var/lib/wazuh-indexer
            - name: wazuh-certificates
              mountPath: /usr/share/wazuh-indexer/config/certs/node-key.pem
              subPath: node-key.pem
              readOnly: true
            - name: wazuh-certificates
              mountPath: /usr/share/wazuh-indexer/config/certs/node.pem
              subPath: node.pem
              readOnly: true
            - name: wazuh-certificates
              mountPath: /usr/share/wazuh-indexer/config/certs/root-ca.pem
              subPath: root-ca.pem
              readOnly: true
            - name: wazuh-certificates
              mountPath: /usr/share/wazuh-indexer/config/certs/admin.pem
              subPath: admin.pem
              readOnly: true
            - name: wazuh-certificates
              mountPath: /usr/share/wazuh-indexer/config/certs/admin-key.pem
              subPath: admin-key.pem
              readOnly: true
            - name: wazuh-indexer-config
              mountPath: /usr/share/wazuh-indexer/config/opensearch.yml
              subPath: opensearch.yml
              readOnly: true
            - name: wazuh-indexer-config
              mountPath: /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml
              subPath: internal_users.yml
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 9200
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30
          ports:
            - containerPort: 9200
              name: api
            - containerPort: 9300
              name: cluster