apiVersion: v1
kind: Service
metadata:
  name: "wazuh-indexer"
spec:
  selector:
    app.kubernetes.io/name: "wazuh-indexer"
  ports:
    - name: api
      port: 9200
      targetPort: api
    - name: cluster
      port: 9300
      targetPort: cluster