apiVersion: v1
kind: Service
metadata:
  name: "wazuh-manager"
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  selector:
    app.kubernetes.io/name: "wazuh-manager"
  ports:
    - name: cluster
      port: 1516
      targetPort: cluster