apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-indexer-config
data:
  opensearch.yml: |-
    cluster.name: {{ .Values.indexer.environments.cluster_name }}
    network.host: {{ .Values.indexer.environments.network_host }}

    plugins.security.ssl.transport.enabled: true
    plugins.security.ssl.transport.pemcert_filepath: /usr/share/wazuh-indexer/certs/node.pem
    plugins.security.ssl.transport.pemkey_filepath: /usr/share/wazuh-indexer/certs/node-key.pem
    plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/root-ca.pem
    plugins.security.ssl.transport.enforce_hostname_verification: false

    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemcert_filepath: /usr/share/wazuh-indexer/certs/node.pem
    plugins.security.ssl.http.pemkey_filepath: /usr/share/wazuh-indexer/certs/node-key.pem
    plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/root-ca.pem

    plugins.security.audit.type: internal_opensearch
    plugins.security.audit.config.index: "'security-auditlog-'YYYY.MM"

    plugins.security.allow_default_init_securityindex: true
    plugins.security.authcz.admin_dn:
      - CN=Admin,OU=Wazuh Cloud,O=Wazuh Cloud,ST=California,C=US
    plugins.security.nodes_dn:
      - 'CN=wazuh-indexer,OU=Wazuh Cloud,O=Wazuh Cloud,ST=California,C=US'

    plugins.security.enable_snapshot_restore_privilege: true
    plugins.security.check_snapshot_restore_write_privileges: true
    plugins.security.restapi.roles_enabled: [
      "all_access",
      "security_rest_api_access",
      "service_full_access"
    ]

    opendistro.index_state_management.history.enabled: false

    node.max_local_storage_nodes: 5

    cluster.routing.allocation.disk.watermark.low: "95%"
    cluster.routing.allocation.disk.watermark.high: "95%"
    cluster.routing.allocation.disk.watermark.flood_stage: "99%"

    path.data: /usr/share/wazuh-indexer/data
    path.logs: /var/log/wazuh-indexer
    compatibility.override_main_response_version: true
    plugins.security.ssl.transport.resolve_hostname: false
    plugins.security.system_indices.enabled: true
    plugins.security.system_indices.indices: [
      ".opendistro-alerting-config", 
      ".opendistro-alerting-alert*", 
      ".opendistro-reports-*", 
      ".opendistro-notifications-*", 
      ".opendistro-notebooks", 
      ".replication-metadata-store"
    ]

  internal_users.yml: |-
    _meta:
      type: "internalusers"
      config_version: 2

    admin:
      hash: "$2y$12$K/SpwjtB.wOHJ/Nc6GVRDuc1h0rM1DfvziFRNPtk27P.c4yDr9njO"
      reserved: true
      backend_roles:
      - "admin"
      description: "Demo admin user"

    kibanaserver:
      hash: "$2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H."
      reserved: true
      description: "Demo kibanaserver user"

    kibanaro:
      hash: "$2a$12$JJSXNfTowz7Uu5ttXfeYpeYE0arACvcwlPBStB1F.MI7f0U9Z4DGC"
      reserved: false
      backend_roles:
      - "kibanauser"
      - "readall"
      attributes:
        attribute1: "value1"
        attribute2: "value2"
        attribute3: "value3"
      description: "Demo kibanaro user"

    logstash:
      hash: "$2a$12$u1ShR4l4uBS3Uv59Pa2y5.1uQuZBrZtmNfqB3iM/.jL0XoV9sghS2"
      reserved: false
      backend_roles:
      - "logstash"
      description: "Demo logstash user"

    readall:
      hash: "$2a$12$ae4ycwzwvLtZxwZ82RmiEunBbIPiAmGZduBAjKN0TXdwQFtCwARz2"
      reserved: false
      backend_roles:
      - "readall"
      description: "Demo readall user"

    snapshotrestore:
      hash: "$2y$12$DpwmetHKwgYnorbgdvORCenv4NAK8cPUg8AI6pxLCuWf/ALc0.v7W"
      reserved: false
      backend_roles:
      - "snapshotrestore"
      description: "Demo snapshotrestore user"

