apiVersion: v1
kind: Secret
metadata:
  name: wazuh-indexer-certs
type: Opaque
stringData:
  admin-key.pem: |-
    -----BEGIN PRIVATE KEY-----
    MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQCv9LS+C8THVNqL
    9hec84GxM5sNzMCFpAYKKzLB4ckoOsla4Pe8jjP27mvkKAd+WJ/HzIq4h5cXDTxu
    ri83vG6Vv7djNUzE+RVScouk9Ur2B7MpiSTrejGhZD/19e8RCTComCvx2T5aV/AM
    r2m1w2awBkJUQjRK6Gn1gLottFu/rTaxcwCeGKFD6YeMHxyjFmV2vRzswGF3aofe
    wpYusQCKWAGbcdK+03wsw4ErtTI76Pf/P2Xz/swfQcOHcqYvXItewnf57JtONCZR
    jUYLGM026itC0o9YyTPHBHX0/yQsxddSL9hakCbbbm/TPPeXnhx4vmapsw6G3+7f
    DPQsEXvXAgMBAAECggEBAKpqFVdu7IGmBBjEGrCPAtANzCF8agXFC3hzyDARLpMB
    BJ04/5cmHtwMpIAP6NoMmYuX5c68u6++yQXlO6P+oxfz23iBWb34BBebCvaT/6rz
    YCldQ12xNjo6btwX+heE0BSpdP5CSmqTetG+XmKFQoI/PaR/jkfyexUkPK0hXi7v
    xwxl4p06FQacOt970Xm3xRcum8ZLkaAF1JcwQLGABWKgTDfW56NcXwTvHEFSRCD9
    qRA4Ut/C+MaPzjQ2XzSRJ747EvdKcGtk/9nEpZ0wMFiiVBQom6eTJu6WYLf7qWwJ
    tSVFmGiyrsLhb0rNj8OUNxbTPM+9+pL6xO+aadXTbZECgYEA4VTPrukR+3x4V1eQ
    FI9WLR1/4vic3qPNcIwempsaIC9MNuSHo2ickYs6CFlBAHMF/kxpAqKkQq6H7ecY
    Hs7cP77nO0hrgMjtEbSXyLKbSLrlsNVD0ebZmMccCB0dAUY8h1ZKbUpR6l9PrJwy
    XpbM05dBaX3YfToUf7BIECEKoXkCgYEAx+eDh4OE/723j9V6HZBeNr9irtg2HM7l
    oDz3eo4a9/KDu2uGh8i1ku5/iptXjH2Xaber9Uys/mOiw/TxoaIm/aUQYs09M52t
    SP5NccE/7aB+wychg2skCgj1CzGLS655ZpL2DGYV6haOGDjXPposIUx4zMbiGKea
    5Ru19USYg88CgYEAhyA6DzUboIlrDU2oTHwMfK+VEoJuaCEowNZ2P9bFWwmiFcUE
    Bh1kzu8EFR+ZGHDh5jbiPj9Ua9yIDUWpNEhu0hdkSSvLtAZKDHUVFLju4DWcKmgp
    7IUYdkLo74Ct9Saug6ZeqZ2I9BjGCcf9eLXMDRNGmcFrAuXChzQqcumtm1kCgYEA
    vErDR0eIZOMsHZz0sxgixeqrZwlcnvH6tF34tUVY/ac+kbCMPSW+cbGYDNSZOEmr
    7vYEUL9ySwNKcs0rNBXqKAvsTUQIm6+vYwu1oqpmLst32xXmqUSn45PgTDTUgerL
    iuRuQet+RMoN+Z7Aj8TkQFEpj6jdml90tMzPLUD5b10CgYEAsYmvDHaxMrjxOcED
    vT3iSxg3De/dQl2fYufkSmgWk0zhd8Jyo7YT4PwzyqPy2kdvHwwLRaFkiq1zK19N
    FxV1tMOr+pE/KF0vgJUcyO64wu9qt7FprpRxWTpbNYnkr/3xTaKl0NIPkFdijKmt
    QLXvYx+fwmxxvCENW3cTrQm3AW0=
    -----END PRIVATE KEY-----
  admin.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIDDjCCAfYCFCd3eIZs1MbKBrzwC7OEQnq9lD6zMA0GCSqGSIb3DQEBCwUAMDUx
    DjAMBgNVBAsMBVdhenVoMQ4wDAYDVQQKDAVXYXp1aDETMBEGA1UEBwwKQ2FsaWZv
    cm5pYTAeFw0yMzEwMTUyMDIyMTVaFw0zMzEwMTIyMDIyMTVaMFIxCzAJBgNVBAYT
    AlVTMRMwEQYDVQQHDApDYWxpZm9ybmlhMQ4wDAYDVQQKDAVXYXp1aDEOMAwGA1UE
    CwwFV2F6dWgxDjAMBgNVBAMMBWFkbWluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEAr/S0vgvEx1Tai/YXnPOBsTObDczAhaQGCisyweHJKDrJWuD3vI4z
    9u5r5CgHflifx8yKuIeXFw08bq4vN7xulb+3YzVMxPkVUnKLpPVK9gezKYkk63ox
    oWQ/9fXvEQkwqJgr8dk+WlfwDK9ptcNmsAZCVEI0Suhp9YC6LbRbv602sXMAnhih
    Q+mHjB8coxZldr0c7MBhd2qH3sKWLrEAilgBm3HSvtN8LMOBK7UyO+j3/z9l8/7M
    H0HDh3KmL1yLXsJ3+eybTjQmUY1GCxjNNuorQtKPWMkzxwR19P8kLMXXUi/YWpAm
    225v0zz3l54ceL5mqbMOht/u3wz0LBF71wIDAQABMA0GCSqGSIb3DQEBCwUAA4IB
    AQBFp0Cz4U2Vu/mFH+SJNyxnij7hdKrnnPDy9NZJhgpTtEwFo5uwzu4ofCHqVcFt
    Cijt8ZxxKZBfBzS6r7x9CSZEQRUJuj6midcX9OhIF3AZchuSiwiFmU3iT6Fyqqjk
    wSiDXGfePAEI4mATuW0p9ARI6vNhZtCVh6/FX+ZIRv2K3jXyt//5MF19oWq0TiTp
    BTVyisoKopCU5ykHOTNCgCNo6MrPBPDhETCO0m86K2agFCZJGg5rSIJaKw7VL9Rq
    cG2zTw/rRnGZINdU5hAEh7ntiDyWNEvrhkwwwfkqeOVkIgnnJhTgbCNk5hZToBhh
    aeHewL6nqg0FFteO0H8JRpZ6
    -----END CERTIFICATE-----
  root-ca-manager.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDYNvRpK29L8EdV
    4MbDk6SQJ/wxlwxrvuWjPV91RLCtUG7Tn46IIDtcfPKpWv/dj4K960TjGRRsjw7C
    m6iaMo9IlvjiNg1uhsWzPkZH6u56f1p50d8KtrEUuGPN/DR4q7JXkNDm6rB5MwDW
    2gLLcvQj1XQKbq3Q0HW4de3tI/SgthwNKJyJWTYdkEKhY5LIslAZ7mJHsoC9KlnZ
    h+JmWQRa6UgQPS/UGnerURavC1YvpP1w60MvQ4IzX2swQ+gGCoJCR7MT51qMgyjY
    dtlXFKHfMrufScbP7u4keFhqLzw56cVQ7FcPkxmjTTeqtonI6bJE7b2Uu1scwiJN
    h243WbkRAgMBAAECggEABk377IEmuqkj+14VjahleQqhcPS9mPq1CYCFow7AtB0P
    Tj5t0oxWDslZ7hRIN7aykkUk+hZGITA+tvABB5YH1Y8JbNc0pw9o/mQHeptgHtRN
    2BWFknNnUHpb9qqvAQHIroL7hHA9extAoAM1Z6dPdSgJPTCjAt7BQAK4UFznCjSX
    fPJP+3c37CZRMhNQsuMf0uPpVEIo7HoOWzP4dNO39D/2vQsWLsIdrWTJyKE02pn/
    qkX7JB4z0NpM3IlkuMowqTdFhREQ3OId1FmLf3ihoCqpU92eziE7yJl4qt3arRaE
    5Lkyrp88rM6BJ/v02CGizk3T29K5llwWtH1w5JnDwQKBgQDx+FK8h/kbfjbfTEot
    alL7Mf7dIYeSxyXwjOPruOL/floyf2pPL16ngLv51TdTx2MRFFVkJ949ajWa9qrI
    I6jpln4xUSkUng8GJ4anOW5Gr2m4CPlDsVXl9eJ1mD0t2ltP7QzGDAi9ZF3bEqWM
    h3UMg096ka5ShiDZSn1d6t+LKQKBgQDkwFUl1DQc2blkWfzCLTt4AHxrAP6yqjKm
    fCcoRTc4cN10AekVtoKv8oY4H31FjC3LGlJu49mOUrncK101j70qXdSpO+ZWSBOW
    gVT0fdETraucO37oKOhZQDv2VUqqciakHDEYNHJ5tiLxF3LN0lZhcbFDMVLFuvoX
    xUN7VAZjqQKBgCBXyPdaVXnPTRZb5C5d3+mjrSVxreV4qSGWM4D2naD5CqVlUphz
    BHvvQTELxvFz3VITHbbdfV9IKxIjloBaA+H1M7jz2EHhPrDb56vCiXL5T3BCAs+B
    jLHIRBTj3ImcfkgYr3Rpd2GZYNI/k9FM6eBaTO1dO6fcNdfVlRxQoMDBAoGBAKSX
    Kuz8Ib78faOSCAbjKt3uY5dOcPS295jIzhfwrYnj08OruD1SQ/g7ZY2uQqGu+igg
    OV3mfdwk8+xSG0/1q6N3PhPCsLo2RDnPtwPwH2asWEUine6HuJ63VC2rMv0vA1Sj
    oEONQS0H+15Dg+xKQrL8bhItxCPXpClEW4i6bZp5AoGALDAi/ESvhV4MkpiN3nUY
    7J6C9Ik0jFBOBG4m34OOaRM3mRHX4WspxjQILRBlfBwJCOlHaPzJsPAbn9AUzF9q
    TpyhT0ljcItw3kC/nPMKDrcvaQ1YPp3lc+7LkcCdIv7abc+erxs3zZAyjPYsN5e4
    qJ9D68QqU7Exz1DTNkosvRw=
    -----END PRIVATE KEY-----
  root-ca-manager.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIUVZZKdrOlum4mFlt25AVoM/Uqhl8wDQYJKoZIhvcNAQEL
    BQAwNTEOMAwGA1UECwwFV2F6dWgxDjAMBgNVBAoMBVdhenVoMRMwEQYDVQQHDApD
    YWxpZm9ybmlhMB4XDTIzMTAxNTIwMjIxNVoXDTMzMTAxMjIwMjIxNVowNTEOMAwG
    A1UECwwFV2F6dWgxDjAMBgNVBAoMBVdhenVoMRMwEQYDVQQHDApDYWxpZm9ybmlh
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2Db0aStvS/BHVeDGw5Ok
    kCf8MZcMa77loz1fdUSwrVBu05+OiCA7XHzyqVr/3Y+CvetE4xkUbI8OwpuomjKP
    SJb44jYNbobFsz5GR+ruen9aedHfCraxFLhjzfw0eKuyV5DQ5uqweTMA1toCy3L0
    I9V0Cm6t0NB1uHXt7SP0oLYcDSiciVk2HZBCoWOSyLJQGe5iR7KAvSpZ2YfiZlkE
    WulIED0v1Bp3q1EWrwtWL6T9cOtDL0OCM19rMEPoBgqCQkezE+dajIMo2HbZVxSh
    3zK7n0nGz+7uJHhYai88OenFUOxXD5MZo003qraJyOmyRO29lLtbHMIiTYduN1m5
    EQIDAQABo1MwUTAdBgNVHQ4EFgQUrocEoyXgHL8nbPdw4iTlBs2Ttz8wHwYDVR0j
    BBgwFoAUrocEoyXgHL8nbPdw4iTlBs2Ttz8wDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAQEAMKXD/P8U4ZKiPFr7dAS4+s8Toq6CvCUomOPAjLaXU8OE
    CpaUTN4nc+TdSvgWYBr+9GFyisjQ8rCUHdwaXq5WxncYJRgzLxcKBS/XIUvtTDAf
    jM7VyYdZ7eUTOElG+VvMH6+iNoq9C/wLX1jvc3mzYMl26kOsaIh4aDy+B+VXYi2e
    EwB+SVO8ARI6TZYAlhnskI8SGH51yCqzea5VneRZQfpbDlb2Pnt3TjLbzmMARj01
    HNYRscMulznbslWUErj2bZD0fXG2r30z4KZfEE/Kj5maUxnMdpa4sjXdrjLaGSUk
    IXymOvsU4SaY1RuIxe1ZeHHVri3SQfkkHKl460HGYg==
    -----END CERTIFICATE-----
  root-ca.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDYNvRpK29L8EdV
    4MbDk6SQJ/wxlwxrvuWjPV91RLCtUG7Tn46IIDtcfPKpWv/dj4K960TjGRRsjw7C
    m6iaMo9IlvjiNg1uhsWzPkZH6u56f1p50d8KtrEUuGPN/DR4q7JXkNDm6rB5MwDW
    2gLLcvQj1XQKbq3Q0HW4de3tI/SgthwNKJyJWTYdkEKhY5LIslAZ7mJHsoC9KlnZ
    h+JmWQRa6UgQPS/UGnerURavC1YvpP1w60MvQ4IzX2swQ+gGCoJCR7MT51qMgyjY
    dtlXFKHfMrufScbP7u4keFhqLzw56cVQ7FcPkxmjTTeqtonI6bJE7b2Uu1scwiJN
    h243WbkRAgMBAAECggEABk377IEmuqkj+14VjahleQqhcPS9mPq1CYCFow7AtB0P
    Tj5t0oxWDslZ7hRIN7aykkUk+hZGITA+tvABB5YH1Y8JbNc0pw9o/mQHeptgHtRN
    2BWFknNnUHpb9qqvAQHIroL7hHA9extAoAM1Z6dPdSgJPTCjAt7BQAK4UFznCjSX
    fPJP+3c37CZRMhNQsuMf0uPpVEIo7HoOWzP4dNO39D/2vQsWLsIdrWTJyKE02pn/
    qkX7JB4z0NpM3IlkuMowqTdFhREQ3OId1FmLf3ihoCqpU92eziE7yJl4qt3arRaE
    5Lkyrp88rM6BJ/v02CGizk3T29K5llwWtH1w5JnDwQKBgQDx+FK8h/kbfjbfTEot
    alL7Mf7dIYeSxyXwjOPruOL/floyf2pPL16ngLv51TdTx2MRFFVkJ949ajWa9qrI
    I6jpln4xUSkUng8GJ4anOW5Gr2m4CPlDsVXl9eJ1mD0t2ltP7QzGDAi9ZF3bEqWM
    h3UMg096ka5ShiDZSn1d6t+LKQKBgQDkwFUl1DQc2blkWfzCLTt4AHxrAP6yqjKm
    fCcoRTc4cN10AekVtoKv8oY4H31FjC3LGlJu49mOUrncK101j70qXdSpO+ZWSBOW
    gVT0fdETraucO37oKOhZQDv2VUqqciakHDEYNHJ5tiLxF3LN0lZhcbFDMVLFuvoX
    xUN7VAZjqQKBgCBXyPdaVXnPTRZb5C5d3+mjrSVxreV4qSGWM4D2naD5CqVlUphz
    BHvvQTELxvFz3VITHbbdfV9IKxIjloBaA+H1M7jz2EHhPrDb56vCiXL5T3BCAs+B
    jLHIRBTj3ImcfkgYr3Rpd2GZYNI/k9FM6eBaTO1dO6fcNdfVlRxQoMDBAoGBAKSX
    Kuz8Ib78faOSCAbjKt3uY5dOcPS295jIzhfwrYnj08OruD1SQ/g7ZY2uQqGu+igg
    OV3mfdwk8+xSG0/1q6N3PhPCsLo2RDnPtwPwH2asWEUine6HuJ63VC2rMv0vA1Sj
    oEONQS0H+15Dg+xKQrL8bhItxCPXpClEW4i6bZp5AoGALDAi/ESvhV4MkpiN3nUY
    7J6C9Ik0jFBOBG4m34OOaRM3mRHX4WspxjQILRBlfBwJCOlHaPzJsPAbn9AUzF9q
    TpyhT0ljcItw3kC/nPMKDrcvaQ1YPp3lc+7LkcCdIv7abc+erxs3zZAyjPYsN5e4
    qJ9D68QqU7Exz1DTNkosvRw=
    -----END PRIVATE KEY-----
  root-ca.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIUVZZKdrOlum4mFlt25AVoM/Uqhl8wDQYJKoZIhvcNAQEL
    BQAwNTEOMAwGA1UECwwFV2F6dWgxDjAMBgNVBAoMBVdhenVoMRMwEQYDVQQHDApD
    YWxpZm9ybmlhMB4XDTIzMTAxNTIwMjIxNVoXDTMzMTAxMjIwMjIxNVowNTEOMAwG
    A1UECwwFV2F6dWgxDjAMBgNVBAoMBVdhenVoMRMwEQYDVQQHDApDYWxpZm9ybmlh
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2Db0aStvS/BHVeDGw5Ok
    kCf8MZcMa77loz1fdUSwrVBu05+OiCA7XHzyqVr/3Y+CvetE4xkUbI8OwpuomjKP
    SJb44jYNbobFsz5GR+ruen9aedHfCraxFLhjzfw0eKuyV5DQ5uqweTMA1toCy3L0
    I9V0Cm6t0NB1uHXt7SP0oLYcDSiciVk2HZBCoWOSyLJQGe5iR7KAvSpZ2YfiZlkE
    WulIED0v1Bp3q1EWrwtWL6T9cOtDL0OCM19rMEPoBgqCQkezE+dajIMo2HbZVxSh
    3zK7n0nGz+7uJHhYai88OenFUOxXD5MZo003qraJyOmyRO29lLtbHMIiTYduN1m5
    EQIDAQABo1MwUTAdBgNVHQ4EFgQUrocEoyXgHL8nbPdw4iTlBs2Ttz8wHwYDVR0j
    BBgwFoAUrocEoyXgHL8nbPdw4iTlBs2Ttz8wDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAQEAMKXD/P8U4ZKiPFr7dAS4+s8Toq6CvCUomOPAjLaXU8OE
    CpaUTN4nc+TdSvgWYBr+9GFyisjQ8rCUHdwaXq5WxncYJRgzLxcKBS/XIUvtTDAf
    jM7VyYdZ7eUTOElG+VvMH6+iNoq9C/wLX1jvc3mzYMl26kOsaIh4aDy+B+VXYi2e
    EwB+SVO8ARI6TZYAlhnskI8SGH51yCqzea5VneRZQfpbDlb2Pnt3TjLbzmMARj01
    HNYRscMulznbslWUErj2bZD0fXG2r30z4KZfEE/Kj5maUxnMdpa4sjXdrjLaGSUk
    IXymOvsU4SaY1RuIxe1ZeHHVri3SQfkkHKl460HGYg==
    -----END CERTIFICATE-----
  wazuh.dashboard-key.pem: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDjH49cpbdUrdux
    OCuSu+Oxh1zS3eX/zIIZqBD3hsbismexlGXrZfTfXEZlBS+7vKuokPkGwDF/utds
    6xwKQ8c/TogNyGq4fBo2kzCnTN2yaI1A1DhNj/w9gGz5/J/tDYLq0js+XHlsJDUl
    ORoiDc5VkwMSiPFwAzOuXFpMvHsD5DB7F4JMwmHeROe6wV7HkxzbDsGm7ITyjmpQ
    xSgCO3FwYNj0KizvfKDRXSi2Y0yREJJ4iyvYmHNBy+4FdbAgKcV57HPlpTBo29qQ
    5anWV3q3ZoqtivOJBtBNGn9FRp6AICmPqDw8gwB7X9KSvt/TYTJAfnvl66IZ9Cz1
    1dAIHyyjAgMBAAECggEAcjcDxCZ93DKWATfrCZ488aDNuCjoqctxPW+8II4BZC0t
    YirrWgZqrwxbRh/mkjVd6aYF5TQvcDlIbjiJYEwXXamjV7MKn/2gvQMl+2v3LOnQ
    5uIR8kdPJKp5ovk8f1xFEstoCYM9eHl41GAz2R4yPexxJhgBuj+R9MPykRZTkm9y
    petjCnlCtLi4/6W7GB3aAR7C0lPX91n9fEPhnhiDIYnZ66TzDkLVfR9etHf4OA/a
    wxvA7sJ1FBP6K1p8bk7X4IZUSGn3MKoc68pwtFUKrs/O+I+gGJlvXenRf8ZXT0PF
    CWkD+1yncyGaaRJcBAEwlGw6sT9kI+oBOrUBCdAtmQKBgQD4Tq05CbkkIXAV5YL4
    Pr2vhNrcBrvcvNQ/j8HE2J1ElQLtW9VBNG7oca5aqmLlEdBraljYlq5tPu7MKSHs
    RRE9iVJBjVNUwR/kjqsf6Krwl/jLCXk7O5S8JO6GkrdSWFdDkpKM+ZhckPPb3ODN
    Pefrgwc9W/0zcG7dcZmQXacDNwKBgQDqKN9yWKa42RY9yxft21O6miwBZQK1d8LA
    Z4jGcRJoxspWl1qf6Ja0m1UC+itiqFVYHdQ2I+GWygT0kIxYvatuqTE5ue86FQvy
    u0KbBuHTaYFjFAE/T6XD5/hmBfJ9ha4Y9XbVCGPJaXw9l9rZK4VPzNzkOFa93fWX
    cJzBrN4v9QKBgQC0fsRuPMInIGNQl2gvubO63ZEV9ZMjruN+XKpWw7r2OndJQMLw
    xgOE1fYOk+KVbvCY1FJHBqk+YkvFfnTZQY95stNnMSsM5eGgC5Ea/c8cWuwP8w/7
    3aCNby8wBYBazDqKtQXwkhKN3xRUkueaadCnIrTlhnO0q5r7P3OIPHuF2wKBgQCZ
    EI6/2GNjgcSgMBo8SZq55/3MC5NxvA96ZjNqRI+cHhY19EoxLYEWHlO71nx1yUPA
    jf8iROI6B2Sl2bdkatedRsv+yCQw+4EL8ozfeeg0oksJ0RHfqNja7s/ZIRoaI0Bi
    4FIFf657ApFMUe+k9mX2fBwIsytAgc8AZ4SQtcen4QKBgBoA3nJTkhnGD4WcMD7V
    IHKHrs0bzjgfJKnbVA1uJnK04G+Z5Wt/U4Fy7txkxOotJgAAbnN5ZAehsL5CSjtA
    e7r4UDog6oHGakQUwH/q5/sbELhgsArlSndDDQnV+AMSfDeQEIdjgYmPO3dNvK+K
    oiCLHwlkNUDls30wTd7KyATr
    -----END PRIVATE KEY-----
  wazuh.dashboard.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIDdjCCAl6gAwIBAgIUJ3d4hmzUxsoGvPALs4RCer2UPrYwDQYJKoZIhvcNAQEL
    BQAwNTEOMAwGA1UECwwFV2F6dWgxDjAMBgNVBAoMBVdhenVoMRMwEQYDVQQHDApD
    YWxpZm9ybmlhMB4XDTIzMTAxNTIwMjIxNloXDTMzMTAxMjIwMjIxNlowXDELMAkG
    A1UEBhMCVVMxEzARBgNVBAcMCkNhbGlmb3JuaWExDjAMBgNVBAoMBVdhenVoMQ4w
    DAYDVQQLDAVXYXp1aDEYMBYGA1UEAwwPd2F6dWguZGFzaGJvYXJkMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4x+PXKW3VK3bsTgrkrvjsYdc0t3l/8yC
    GagQ94bG4rJnsZRl62X031xGZQUvu7yrqJD5BsAxf7rXbOscCkPHP06IDchquHwa
    NpMwp0zdsmiNQNQ4TY/8PYBs+fyf7Q2C6tI7Plx5bCQ1JTkaIg3OVZMDEojxcAMz
    rlxaTLx7A+QwexeCTMJh3kTnusFex5Mc2w7BpuyE8o5qUMUoAjtxcGDY9Cos73yg
    0V0otmNMkRCSeIsr2JhzQcvuBXWwICnFeexz5aUwaNvakOWp1ld6t2aKrYrziQbQ
    TRp/RUaegCApj6g8PIMAe1/Skr7f02EyQH575euiGfQs9dXQCB8sowIDAQABo1cw
    VTAfBgNVHSMEGDAWgBSuhwSjJeAcvyds93DiJOUGzZO3PzAJBgNVHRMEAjAAMAsG
    A1UdDwQEAwIE8DAaBgNVHREEEzARgg93YXp1aC5kYXNoYm9hcmQwDQYJKoZIhvcN
    AQELBQADggEBAB1C8VT5A39vxxdV8vyi23xAKNhY0pdkZwM2xQK3Wp52tUQoAMQN
    9LbuBgJvi8vVr9veCNfO/0T/3wrhwcSS3ugverCUBnQ55MbAO0ncK9BYn9V4pXDs
    rrXPKcgo/jyht+2SQWbFQPVv7IUSH5Zp9OOlVM1sv7X/VIdJO3BAAY2+MfG2BAbX
    JnavpL9ttK52RFwu3DgIK1KtyAherg53QJgD4xtcsv3JhqAts1zmRo80TWrhE9TT
    kJaYfNowIGEegf9sJLsqwGTsJSTnFjsE6SSRItE0L/bLyO19Mbs0XlsIjH4GrSjm
    pobgjDB55gb1jZJvvADonwsba1hS7yXTyso=
    -----END CERTIFICATE-----
  wazuh.indexer-key.pem: |-
    -----BEGIN PRIVATE KEY-----
    MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQD2+/+rQmgHDjrs
    Bkt948O09M4uBW170p7EoX3z0PLWU5TkSx4JackRrRa1nDW5QuPF5JvIiWbJLxyI
    81h54yKlsrgjT4BewjIby3+JKR430HvpylK+Um293WpV08Sjy4489p83zp99hlwY
    16RQwFUJLSdMhLeTC0PcYfT2sF/+c7yGv81pDMsoVuRDqpEG2SqLQXGcZ8TIAw4u
    NN5y2HTGj7lZagM5ucZ1SkepeUqbt70cdCmv91RjwJbhSdMtzWMhJDlJuKw9KMqT
    99dPrmh6HoH3WGfXfX+ienWDhuuidb4op2frQEb0np37KTOKGRdV2NrOYdU36jrq
    vNl/jdO5AgMBAAECggEBAImmJnafGvUbtDEIzRgLUW5PpX02ny8MUloKGvVAtaZH
    jMqzJrleUKZeTjLHLZXjtqf64eug0D092WxmGyBLO2sXsNJVI5ksJ9sfziN2XBYF
    RpoknXre27Seav4MeSJEdzB4zoG+0VqXAEsEG9q5Zmsn1CgsK1dzRs3Tdj/qSoW3
    iMFU3wFxyIg2eeQviYuR+q4fmvSUsAjQZ1UipZ8y235FUeiUNVXtJRX867UJgkYh
    5IP5mpOITTa5gDvJIzHKwhyM6V9tt6dAyE3p7yVxPbicwZHbfkZwlllzj5wrREP4
    BWKlaCyu7YMyHfgR2Don3Rp7afKZVXQ95KU5PKDpFlECgYEA/0OA0nsUHv9zqPFN
    mO9hdGdSxQt/8mEEL1+io4qb0OhhuWr9pDgLGsSaFbeJnGaUYFS+1Mdnm7TTpAn+
    jpQSw0UcEVJwMsSRHMY49oM0QIV3+pZzNuHSBd2MsyIQHDgP/ThX7fmYmBn9eGV5
    B0VZdLQPdr2sFtlUBOcqB4PzihUCgYEA97JhuI9jRV/PLbSwH+MvQHI71aE+7JWE
    gD8AR0zMFFFYHWztFUdudknYvmPAkk7C8Yfnzk8BGywSStQk+LOexZJ8wbXz2TZ7
    RJhinNEZrziuultfL+w8n9kry2yRKupF1vS8CdYEqWSqUf+xKoX5BbbfceMAwKLm
    aiNopEilgBUCgYEAiH+rUmJYZx8I1S175i0TuvBJdW7p002HtGF6keNb4QFyyHjq
    +zaw0XaSQsyrfIPqEf0fMp8Sy1ON3OkvQ0TxJ5Q8JxMjRjKQuodRDJkqhtoYR1rO
    b2mgKlzHkT7EyKI+ApVvh6TxsVwsi4YPixDNfjePEVrpvCoo4JpQgkZQI+UCgYEA
    6fsjvIgWqm36853/0d91v1cploAfRLVo2QyqYq/1CCxfJEzFGJjFjA/uIstwGcU0
    +Zv8KTMQRG65SN5lnllu3gumtgX/N2zzvLSGUsRjktXkmD3ACTELg6RObnc8GmH7
    XzcIefIlrS5ehd8XqKetuOwq3xYkm9RF/HU+YBIP5JECgYEA1xO4BHpxDhph2PMT
    8aKwdqrqm18RxeyDIve2GMnS6CILkXwXB5JkDaxj6gwo1jOH5IS6yiCtlmZUPEDI
    TOj1Bbpu2a7l7AsRrtQLHAJZcIParcYsgcU4/MsPhcmjxmKEgf0hft7C8RNhaGs+
    EyixuK2KLhxiiTy/D/EsRAv+zVE=
    -----END PRIVATE KEY-----
  wazuh.indexer.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIDcjCCAlqgAwIBAgIUJ3d4hmzUxsoGvPALs4RCer2UPrQwDQYJKoZIhvcNAQEL
    BQAwNTEOMAwGA1UECwwFV2F6dWgxDjAMBgNVBAoMBVdhenVoMRMwEQYDVQQHDApD
    YWxpZm9ybmlhMB4XDTIzMTAxNTIwMjIxNloXDTMzMTAxMjIwMjIxNlowWjELMAkG
    A1UEBhMCVVMxEzARBgNVBAcMCkNhbGlmb3JuaWExDjAMBgNVBAoMBVdhenVoMQ4w
    DAYDVQQLDAVXYXp1aDEWMBQGA1UEAwwNd2F6dWguaW5kZXhlcjCCASIwDQYJKoZI
    hvcNAQEBBQADggEPADCCAQoCggEBAPb7/6tCaAcOOuwGS33jw7T0zi4FbXvSnsSh
    ffPQ8tZTlORLHglpyRGtFrWcNblC48Xkm8iJZskvHIjzWHnjIqWyuCNPgF7CMhvL
    f4kpHjfQe+nKUr5Sbb3dalXTxKPLjjz2nzfOn32GXBjXpFDAVQktJ0yEt5MLQ9xh
    9PawX/5zvIa/zWkMyyhW5EOqkQbZKotBcZxnxMgDDi403nLYdMaPuVlqAzm5xnVK
    R6l5Spu3vRx0Ka/3VGPAluFJ0y3NYyEkOUm4rD0oypP310+uaHoegfdYZ9d9f6J6
    dYOG66J1viinZ+tARvSenfspM4oZF1XY2s5h1TfqOuq82X+N07kCAwEAAaNVMFMw
    HwYDVR0jBBgwFoAUrocEoyXgHL8nbPdw4iTlBs2Ttz8wCQYDVR0TBAIwADALBgNV
    HQ8EBAMCBPAwGAYDVR0RBBEwD4INd2F6dWguaW5kZXhlcjANBgkqhkiG9w0BAQsF
    AAOCAQEASynccukONEjAh8fWmnKrf7+WBghWfwsJ26zl1ptzhApMbkBHL7EcFmFq
    Y/u8H0j+yV0+QFKiCdntb9CI+8H+LjIq08C/p7jpwrFmdJqpntgRNOIk2xJct8gU
    XGEeORloW2UtaXc7tox4cL3OHe60Ned77RMYx2pRIL+ihlePaDu3KEz01btsxB2i
    d/RPkGSRN/lz7O8Uo9P1ucqL4/tsNhng66IYLz4LYg8UOeDjdtU7CjM8o/7u/8aV
    JSUqqTMaNZEWPhR1Kvzr0F3dA+PbToCa2y13qbiVh5nTdMUe1hDkKBkU0ZTCUWOd
    UZ3QDxpV2Ir0yzOt7HPEASdFV2VkBA==
    -----END CERTIFICATE-----
  wazuh.manager-key.pem: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDH4wxeP8jCpPMR
    4Zu/LlMxckLqMKFw4CpO+xIKNhVPLvg8K4ofPWR8ekDFQu/Tyh2QBxNAnxzSc0fr
    cvo+OKcRF9yxz1IYVYsHfVLdT/NbM8lvHEzhBLm10QqvSFCsQkF5tJSA37wkHUrc
    PndjZhMdAkhTM2ciQWDXmpnuTV4rjciqnDXQM1Q+2LpF+lcK7URWmifdsl+/4/MZ
    dC/kyKaVO4KgbrJZtj0JEQL+aNkqYV5VnKSwqWuioZzCMgY8lLNwdx+xPTuwvx8r
    15jYEYTf+MsX2CXg7O8AjxolqmOWmb94JIAA2Jpsxy1Ql/wMzIbI6fQWIID6of4g
    uH4X3YptAgMBAAECggEBAIXaBvg+IkQljRfWSiNV9CPSbfjBI/qgQfStsEDiQpbJ
    zzULuux8ggPRIfp2fn8Gg5FlC4FkizpqNCj4z5ZG/ak2n3T6bfEZp4YWaB0HYuEZ
    5rPe8aRlM68LEuqZtFwF6i6DvEYojKZqbyzZL72CJx5v3trIOzH3MdBvGNE5QexL
    UIPpjVvLtY/FWX+B55mx50SphIi0li0W/26N2O84BcoDYrd0SQZ3llyr8MdKP1WC
    gjQScMKvur7CLEO2OpuTCHq31CnxZVh3sfCKFINL9PG7Xa3CVPx4hWOu/ZbL18zS
    9TLuLG+SFmFREfjlMvziJrkGGk2iKDCfIcPIHZKpG4ECgYEA6l4qA4NbX+ulFaNu
    OfzwcOPXu+IB2AM0uElrhXmhLcJqP5gm4MsudKxlFis1+xQVA9kDPnAeWgLhSMCD
    WLyAVx2JopJw02+XpF2Lu4mimCAOPkA4hjptaws8XzQf/QsOAixqjsTeBvzrcGda
    ArdzgUdviykZoW7j+HEkWylcWvECgYEA2lYj/+SDwqbVjmqw8D7fnm6XA96EPRuV
    2hNsncoCeKjzath0DjT8WbPvmDM1cTRIRZalnwPiwh0FkzeCVMbr0aUGEKtETBqU
    EekART9na/nE3toSzbSVImyllzLFl+cN3lMXdCiEESXfPfeVzPz6dFTfOYylfkPq
    P30NJWaDzz0CgYBFbTuY6tKoqY+vx0gh2XIInxYLTDormVeGuAkn8w3yFkOPLy1l
    LgtG+MLBPG+zPxGyoBi76E61b2D5Qj4mjUCfjdp11Fej6szLHgMEvRLzaZuOiUu1
    R52eNifeM/y94wZ1Ul8Gh/8Vptq/433gjCOlSloaqUQ0dDsIH8wbTTdUoQKBgQCb
    kwmvyrqANrSw+CD/7y0UDSUaIrIDgOZ0L6cTf9/m7iwUlAuOG/88Q9STlNmdwm1E
    +KUm+3PWcSuJzOHXWq6qAXai5gaSW9XqNSZ2MUmWTLEVQjpnzSb/En+jjw/wvzjI
    lFh/8ma4eU3rL8HUAObNgbRVo3xAzk/Z0VdOsQ922QKBgBkWDr/WrlwSjVy9GrPA
    qcsRnspK698SFVH5ybComzrLcuNyMC9rCpD4aQMp2eBvZdVkwu3frDhN3yF/CRhj
    yKUewN6+9QtlxLC73RrS/eKbhFsrzxjrTBiClDApMTWD7EFORb+VCkvlFBneJSHL
    rZHPQbI2lDYS/RfBY4/GMVxM
    -----END PRIVATE KEY-----
  wazuh.manager.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIDcjCCAlqgAwIBAgIUJ3d4hmzUxsoGvPALs4RCer2UPrUwDQYJKoZIhvcNAQEL
    BQAwNTEOMAwGA1UECwwFV2F6dWgxDjAMBgNVBAoMBVdhenVoMRMwEQYDVQQHDApD
    YWxpZm9ybmlhMB4XDTIzMTAxNTIwMjIxNloXDTMzMTAxMjIwMjIxNlowWjELMAkG
    A1UEBhMCVVMxEzARBgNVBAcMCkNhbGlmb3JuaWExDjAMBgNVBAoMBVdhenVoMQ4w
    DAYDVQQLDAVXYXp1aDEWMBQGA1UEAwwNd2F6dWgubWFuYWdlcjCCASIwDQYJKoZI
    hvcNAQEBBQADggEPADCCAQoCggEBAMfjDF4/yMKk8xHhm78uUzFyQuowoXDgKk77
    Ego2FU8u+Dwrih89ZHx6QMVC79PKHZAHE0CfHNJzR+ty+j44pxEX3LHPUhhViwd9
    Ut1P81szyW8cTOEEubXRCq9IUKxCQXm0lIDfvCQdStw+d2NmEx0CSFMzZyJBYNea
    me5NXiuNyKqcNdAzVD7YukX6VwrtRFaaJ92yX7/j8xl0L+TIppU7gqBuslm2PQkR
    Av5o2SphXlWcpLCpa6KhnMIyBjyUs3B3H7E9O7C/HyvXmNgRhN/4yxfYJeDs7wCP
    GiWqY5aZv3gkgADYmmzHLVCX/AzMhsjp9BYggPqh/iC4fhfdim0CAwEAAaNVMFMw
    HwYDVR0jBBgwFoAUrocEoyXgHL8nbPdw4iTlBs2Ttz8wCQYDVR0TBAIwADALBgNV
    HQ8EBAMCBPAwGAYDVR0RBBEwD4INd2F6dWgubWFuYWdlcjANBgkqhkiG9w0BAQsF
    AAOCAQEAQoYGDlpc2cK8SP8NbAeZTGNuc0Lvzh1PFJuOc6woZr6pnnRl992dBtCw
    1HUz9CcbJY9RAafX3U0etzg7Q3GPijTJQmSY2EF+dFPUGDRdS0vlv2Ol98YezKkW
    gK5pcopUEJYsO22AetpxV9oA0fWQhV5e+ytN+Jaza+Es0wxGTPvkI0lxS+6Dgxua
    z9cokv3b4pAvW7kEmvpA8khK/Xyxq2ktQdT7I6whutzAlRFhgUpU2pLPvubNsPAF
    wL2qmgLOjD4ktbWNJ9CYOJHPnu/rWbHSzFFDf8iXzSGNJUgTbnMRhHEftN74qo7A
    Vqomd7PTdYSF4kIdO2eaMYq+SKfVEg==
    -----END CERTIFICATE-----
