apiVersion: batch/v1
kind: Job
metadata:
  generateName: pre-sync-job-2-
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: pre-sync-job-2
        image: ubuntu
        command:
          - "/bin/bash"
          - "-c"
          - "echo \"PreSync: pre-sync-job-2\""
      restartPolicy: Never
  backoffLimit: 2